blank_issues_enabled: true
contact_links:
  - name: Common Arabic Team
    url: mailto:aramb@aramservices.com
    about: Contact us now.
  - name: Discussions (link coming soon)
    url: 
    about: Please ask and answer questions here.
