name: Request a Different Sticker File Format

description: If you want a different file format not listed here, open an issue on GitHub, and I will supply you with the file format as soon as possible, inshaaAllah.

title: '[File Format Request]'

body:
  - type: markdown
    attributes:
      value: |
        # Welcome!
        This is a form to request a different file format for stickers.

  - type: dropdown
    id: file-format-needed
    attributes:
      label: Which file format do you want?
      description: Choose from the dropdown list which format you need
      required: true
      options:
        - JPEG
        - BMP
        - GIF
        - ASCII ART (.txt)
        - ICO
        - AVIF
        - HEIF
        - PDF
        - RAW (.data, .raw)
        - TIFF
        - SVG

  - type: dropdown
    id: transparency
    attributes:
      label: Do you want the file to be transparent or non-transparent?
      description: Select the transparency option for the sticker
      required: true
      options:
        - Transparent
        - Not Transparent
        
  - type: input
    id: email
    attributes:
      label: Please provide your email so we can email you the file
      description: Enter your email address
      placeholder: example@example.com
      required: true
        

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Provide any additional details or comments (optional)
