name: Request a different sticker file format not listed on website
description: If you want a differnt file format not listed here, open an issue on GitHub, and I will supply you with the file format as soon as possible, inshaaAllah.
assignees:
  - aramb-dev
